//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADImport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADImport.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        internal static string ADAttribute_c {
            get {
                return ResourceManager.GetString("ADAttribute_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ADAttribute_cn {
            get {
                return ResourceManager.GetString("ADAttribute_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string ADAttribute_co {
            get {
                return ResourceManager.GetString("ADAttribute_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string ADAttribute_comment {
            get {
                return ResourceManager.GetString("ADAttribute_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string ADAttribute_company {
            get {
                return ResourceManager.GetString("ADAttribute_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string ADAttribute_department {
            get {
                return ResourceManager.GetString("ADAttribute_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string ADAttribute_division {
            get {
                return ResourceManager.GetString("ADAttribute_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string ADAttribute_employeeID {
            get {
                return ResourceManager.GetString("ADAttribute_employeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax number.
        /// </summary>
        internal static string ADAttribute_facsimileTelephoneNumber {
            get {
                return ResourceManager.GetString("ADAttribute_facsimileTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string ADAttribute_givenName {
            get {
                return ResourceManager.GetString("ADAttribute_givenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home folder.
        /// </summary>
        internal static string ADAttribute_homeDirectory {
            get {
                return ResourceManager.GetString("ADAttribute_homeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        internal static string ADAttribute_homePhone {
            get {
                return ResourceManager.GetString("ADAttribute_homePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address.
        /// </summary>
        internal static string ADAttribute_homePostalAddress {
            get {
                return ResourceManager.GetString("ADAttribute_homePostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string ADAttribute_info {
            get {
                return ResourceManager.GetString("ADAttribute_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials.
        /// </summary>
        internal static string ADAttribute_initials {
            get {
                return ResourceManager.GetString("ADAttribute_initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Phone.
        /// </summary>
        internal static string ADAttribute_ipPhone {
            get {
                return ResourceManager.GetString("ADAttribute_ipPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string ADAttribute_l {
            get {
                return ResourceManager.GetString("ADAttribute_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logon.
        /// </summary>
        internal static string ADAttribute_lastLogon {
            get {
                return ResourceManager.GetString("ADAttribute_lastLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string ADAttribute_mail {
            get {
                return ResourceManager.GetString("ADAttribute_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string ADAttribute_middleName {
            get {
                return ResourceManager.GetString("ADAttribute_middleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        internal static string ADAttribute_mobile {
            get {
                return ResourceManager.GetString("ADAttribute_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string ADAttribute_none {
            get {
                return ResourceManager.GetString("ADAttribute_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object SID.
        /// </summary>
        internal static string ADAttribute_objectSid {
            get {
                return ResourceManager.GetString("ADAttribute_objectSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax number - others.
        /// </summary>
        internal static string ADAttribute_otherFacsimileTelephoneNumber {
            get {
                return ResourceManager.GetString("ADAttribute_otherFacsimileTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone - others.
        /// </summary>
        internal static string ADAttribute_otherHomePhone {
            get {
                return ResourceManager.GetString("ADAttribute_otherHomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Phone - others.
        /// </summary>
        internal static string ADAttribute_otherIpPhone {
            get {
                return ResourceManager.GetString("ADAttribute_otherIpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address - others.
        /// </summary>
        internal static string ADAttribute_otherMailbox {
            get {
                return ResourceManager.GetString("ADAttribute_otherMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number - others.
        /// </summary>
        internal static string ADAttribute_otherMobile {
            get {
                return ResourceManager.GetString("ADAttribute_otherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager number - others.
        /// </summary>
        internal static string ADAttribute_otherPager {
            get {
                return ResourceManager.GetString("ADAttribute_otherPager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number - others.
        /// </summary>
        internal static string ADAttribute_otherTelephone {
            get {
                return ResourceManager.GetString("ADAttribute_otherTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager number.
        /// </summary>
        internal static string ADAttribute_pager {
            get {
                return ResourceManager.GetString("ADAttribute_pager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ADAttribute_personalTitle {
            get {
                return ResourceManager.GetString("ADAttribute_personalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office location.
        /// </summary>
        internal static string ADAttribute_physicalDeliveryOfficeName {
            get {
                return ResourceManager.GetString("ADAttribute_physicalDeliveryOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal address.
        /// </summary>
        internal static string ADAttribute_postalAddress {
            get {
                return ResourceManager.GetString("ADAttribute_postalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP / Postal code.
        /// </summary>
        internal static string ADAttribute_postalCode {
            get {
                return ResourceManager.GetString("ADAttribute_postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O. Box.
        /// </summary>
        internal static string ADAttribute_postOfficeBox {
            get {
                return ResourceManager.GetString("ADAttribute_postOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telex number.
        /// </summary>
        internal static string ADAttribute_primaryTelexNumber {
            get {
                return ResourceManager.GetString("ADAttribute_primaryTelexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon name (pre-Windows 2000).
        /// </summary>
        internal static string ADAttribute_sAMAccountName {
            get {
                return ResourceManager.GetString("ADAttribute_sAMAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string ADAttribute_sn {
            get {
                return ResourceManager.GetString("ADAttribute_sn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / province.
        /// </summary>
        internal static string ADAttribute_st {
            get {
                return ResourceManager.GetString("ADAttribute_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string ADAttribute_street {
            get {
                return ResourceManager.GetString("ADAttribute_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        internal static string ADAttribute_streetAddress {
            get {
                return ResourceManager.GetString("ADAttribute_streetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string ADAttribute_telephoneNumber {
            get {
                return ResourceManager.GetString("ADAttribute_telephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telex number - others.
        /// </summary>
        internal static string ADAttribute_telexNumber {
            get {
                return ResourceManager.GetString("ADAttribute_telexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string ADAttribute_title {
            get {
                return ResourceManager.GetString("ADAttribute_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon name.
        /// </summary>
        internal static string ADAttribute_userPrincipalName {
            get {
                return ResourceManager.GetString("ADAttribute_userPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nThe syntax of this command is: ADIMPORT /profile filename\r\n\r\nfilename - Path leading to the import profile (an XML file with import settings). The path can be specified either relatively or absolutely. Make sure that you use proper quotation.\r\n.
        /// </summary>
        internal static string Console_Help {
            get {
                return ResourceManager.GetString("Console_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading all objects from Active directory..
        /// </summary>
        internal static string Console_LoadingObjectFromAD {
            get {
                return ResourceManager.GetString("Console_LoadingObjectFromAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected import profile: [{0}].
        /// </summary>
        internal static string Console_SelectedImportProfile {
            get {
                return ResourceManager.GetString("Console_SelectedImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the import profile. For more help use the /h selector..
        /// </summary>
        internal static string Console_SpecifyProfile {
            get {
                return ResourceManager.GetString("Console_SpecifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments..
        /// </summary>
        internal static string Error_ArgumentException {
            get {
                return ResourceManager.GetString("Error_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. You have entered invalid username or password..
        /// </summary>
        internal static string Error_BadUsernameOrPassword {
            get {
                return ResourceManager.GetString("Error_BadUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to connect to domain controller. Following error occurred:.
        /// </summary>
        internal static string Error_ConnectingAD {
            get {
                return ResourceManager.GetString("Error_ConnectingAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to establish connection to domain controller. Please check your network connection and logon credentials..
        /// </summary>
        internal static string Error_DCConnectionException {
            get {
                return ResourceManager.GetString("Error_DCConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified directory was not found..
        /// </summary>
        internal static string Error_DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("Error_DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file was not found..
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file was not found..
        /// </summary>
        internal static string Error_FileNotFoundException {
            get {
                return ResourceManager.GetString("Error_FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Error.
        /// </summary>
        internal static string Error_IOErrorCaption {
            get {
                return ResourceManager.GetString("Error_IOErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current account is not a domain account. Please specify credentials manually..
        /// </summary>
        internal static string Error_LocalUserAccountException {
            get {
                return ResourceManager.GetString("Error_LocalUserAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while proceeding to the next step. Please read the following error:.
        /// </summary>
        internal static string Error_MovingStep {
            get {
                return ResourceManager.GetString("Error_MovingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while proceeding to the next step..
        /// </summary>
        internal static string Error_MovingStepCaption {
            get {
                return ResourceManager.GetString("Error_MovingStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify file name..
        /// </summary>
        internal static string Error_NoFilename {
            get {
                return ResourceManager.GetString("Error_NoFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application needs to be run under administrator account..
        /// </summary>
        internal static string Error_NotAdministrator {
            get {
                return ResourceManager.GetString("Error_NotAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions to write..
        /// </summary>
        internal static string Error_NoWritePermissions {
            get {
                return ResourceManager.GetString("Error_NoWritePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is already occupied..
        /// </summary>
        internal static string Error_PathIsOccupied {
            get {
                return ResourceManager.GetString("Error_PathIsOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify directory..
        /// </summary>
        internal static string Error_PathMissingDirectory {
            get {
                return ResourceManager.GetString("Error_PathMissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path doesn&apos;t exist..
        /// </summary>
        internal static string Error_PathNotExist {
            get {
                return ResourceManager.GetString("Error_PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path is not valid..
        /// </summary>
        internal static string Error_PathNotValid {
            get {
                return ResourceManager.GetString("Error_PathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify the path..
        /// </summary>
        internal static string Error_PathRequired {
            get {
                return ResourceManager.GetString("Error_PathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path is too long..
        /// </summary>
        internal static string Error_PathTooLongException {
            get {
                return ResourceManager.GetString("Error_PathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import profile [{0}] doesn&apos;t exist..
        /// </summary>
        internal static string Error_ProfileDoesNotExist {
            get {
                return ResourceManager.GetString("Error_ProfileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified import profile is not valid..
        /// </summary>
        internal static string Error_ProfileIsNotValid {
            get {
                return ResourceManager.GetString("Error_ProfileIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select path to the import profile..
        /// </summary>
        internal static string Error_SelectPath {
            get {
                return ResourceManager.GetString("Error_SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient permissions to write to the file..
        /// </summary>
        internal static string Error_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Error_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import profile path has to end with &apos;.xml&apos; extension..
        /// </summary>
        internal static string Error_WrongExtensionXML {
            get {
                return ResourceManager.GetString("Error_WrongExtensionXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string General_Assign {
            get {
                return ResourceManager.GetString("General_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string General_Browse {
            get {
                return ResourceManager.GetString("General_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentico role name.
        /// </summary>
        internal static string General_CMSRolename {
            get {
                return ResourceManager.GetString("General_CMSRolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentico user name.
        /// </summary>
        internal static string General_CMSUsername {
            get {
                return ResourceManager.GetString("General_CMSUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string General_Connect {
            get {
                return ResourceManager.GetString("General_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string General_DeselectAll {
            get {
                return ResourceManager.GetString("General_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all recursively.
        /// </summary>
        internal static string General_DeselectAllRecursively {
            get {
                return ResourceManager.GetString("General_DeselectAllRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string General_DisplayName {
            get {
                return ResourceManager.GetString("General_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string General_Filter {
            get {
                return ResourceManager.GetString("General_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string General_Fullname {
            get {
                return ResourceManager.GetString("General_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string General_Group {
            get {
                return ResourceManager.GetString("General_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string General_Groupname {
            get {
                return ResourceManager.GetString("General_Groupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string General_Groups {
            get {
                return ResourceManager.GetString("General_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string General_Import {
            get {
                return ResourceManager.GetString("General_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files.
        /// </summary>
        internal static string General_LOGFiles {
            get {
                return ResourceManager.GetString("General_LOGFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string General_None {
            get {
                return ResourceManager.GetString("General_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string General_PathColon {
            get {
                return ResourceManager.GetString("General_PathColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string General_Role {
            get {
                return ResourceManager.GetString("General_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name:.
        /// </summary>
        internal static string General_Rolename {
            get {
                return ResourceManager.GetString("General_Rolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string General_Roles {
            get {
                return ResourceManager.GetString("General_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string General_SelectAll {
            get {
                return ResourceManager.GetString("General_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all recursively.
        /// </summary>
        internal static string General_SelectAllRecursively {
            get {
                return ResourceManager.GetString("General_SelectAllRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string General_Selected {
            get {
                return ResourceManager.GetString("General_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string General_Sitename {
            get {
                return ResourceManager.GetString("General_Sitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string General_Step {
            get {
                return ResourceManager.GetString("General_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string General_TestConnection {
            get {
                return ResourceManager.GetString("General_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string General_User {
            get {
                return ResourceManager.GetString("General_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string General_Username {
            get {
                return ResourceManager.GetString("General_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string General_Users {
            get {
                return ResourceManager.GetString("General_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files.
        /// </summary>
        internal static string General_XMLFiles {
            get {
                return ResourceManager.GetString("General_XMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning user &apos;{0}&apos; to role &apos;{1}&apos;....
        /// </summary>
        internal static string Log_AssigningUserToRole {
            get {
                return ResourceManager.GetString("Log_AssigningUserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting role &apos;{0}&apos;....
        /// </summary>
        internal static string Log_DeletingRole {
            get {
                return ResourceManager.GetString("Log_DeletingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user &apos;{0}&apos;....
        /// </summary>
        internal static string Log_DeletingUser {
            get {
                return ResourceManager.GetString("Log_DeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Error parsing property ({0})..
        /// </summary>
        internal static string Log_ErrorParsingAttr {
            get {
                return ResourceManager.GetString("Log_ErrorParsingAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {0}.
        /// </summary>
        internal static string Log_GeneralWarning {
            get {
                return ResourceManager.GetString("Log_GeneralWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import was canceled..
        /// </summary>
        internal static string Log_ImportCanceled {
            get {
                return ResourceManager.GetString("Log_ImportCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import has successfully finished ({0}h {1}m {2}s)..
        /// </summary>
        internal static string Log_ImportComplete {
            get {
                return ResourceManager.GetString("Log_ImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import has finished with {0} warnings ({1}h {2}m {3}s)..
        /// </summary>
        internal static string Log_ImportCompleteWithWarnings {
            get {
                return ResourceManager.GetString("Log_ImportCompleteWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing role &apos;{0}&apos; to site &apos;{1}&apos;....
        /// </summary>
        internal static string Log_ImportingRole {
            get {
                return ResourceManager.GetString("Log_ImportingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing user &apos;{0}&apos;....
        /// </summary>
        internal static string Log_ImportingUser {
            get {
                return ResourceManager.GetString("Log_ImportingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import profile successfully saved to &quot;{0}&quot;..
        /// </summary>
        internal static string Log_ImportProfileSaved {
            get {
                return ResourceManager.GetString("Log_ImportProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to edit existing role &apos;{0}&apos; because its not marked as domain..
        /// </summary>
        internal static string Log_RoleIsNotDomain {
            get {
                return ResourceManager.GetString("Log_RoleIsNotDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to import role &apos;{0}&apos; becouse a role with this code name already exists..
        /// </summary>
        internal static string Log_RoleNameNotUnique {
            get {
                return ResourceManager.GetString("Log_RoleNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Selected site &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string Log_SiteNotExist {
            get {
                return ResourceManager.GetString("Log_SiteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not belong to any of selected roles and therefore is being skipped....
        /// </summary>
        internal static string Log_SkippingDoesNotBelongToSelectedRole {
            get {
                return ResourceManager.GetString("Log_SkippingDoesNotBelongToSelectedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Impossible to import role with identifier {0} because of empty role name..
        /// </summary>
        internal static string Log_SkippingEmptyRolename {
            get {
                return ResourceManager.GetString("Log_SkippingEmptyRolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Impossible to import user with identifier {0} because of empty user name..
        /// </summary>
        internal static string Log_SkippingEmptyUsername {
            get {
                return ResourceManager.GetString("Log_SkippingEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping user &apos;{0}&apos; which already exists in the database..
        /// </summary>
        internal static string Log_SkippingExistingUser {
            get {
                return ResourceManager.GetString("Log_SkippingExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Skipping object which no longer exists in active directory..
        /// </summary>
        internal static string Log_SkippingNonExistingObject {
            get {
                return ResourceManager.GetString("Log_SkippingNonExistingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating memberships of user &apos;{0}&apos;....
        /// </summary>
        internal static string Log_UpdatingMemberships {
            get {
                return ResourceManager.GetString("Log_UpdatingMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating user &apos;{0}&apos;....
        /// </summary>
        internal static string Log_UpdatingUser {
            get {
                return ResourceManager.GetString("Log_UpdatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to edit existing user &apos;{0}&apos; because this user is not marked as domain..
        /// </summary>
        internal static string Log_UserIsNotDomain {
            get {
                return ResourceManager.GetString("Log_UserIsNotDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: The value of property &apos;{0}&apos; had to be trimmed because it exceeded the maximum length of {1} characters..
        /// </summary>
        internal static string Log_ValueTrimmed {
            get {
                return ResourceManager.GetString("Log_ValueTrimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain\SAM (intranet\DB admins).
        /// </summary>
        internal static string Rolename_Format_DomainAndSAM {
            get {
                return ResourceManager.GetString("Rolename_Format_DomainAndSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid (16-byte number).
        /// </summary>
        internal static string Rolename_Format_Guid {
            get {
                return ResourceManager.GetString("Rolename_Format_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM (DB Admins).
        /// </summary>
        internal static string Rolename_Format_SAM {
            get {
                return ResourceManager.GetString("Rolename_Format_SAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an existing import profile.
        /// </summary>
        internal static string Step1_ExistingImportProfile {
            get {
                return ResourceManager.GetString("Step1_ExistingImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through process of importing data from Active Directory to Kentico. You can select users and groups to be imported defining additional settings like user fields mapping, Kentico roles assignment, save profile for future usage etc..
        /// </summary>
        internal static string Step1_Intro {
            get {
                return ResourceManager.GetString("Step1_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new import profile.
        /// </summary>
        internal static string Step1_NewImportProfile {
            get {
                return ResourceManager.GetString("Step1_NewImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the existing profile?.
        /// </summary>
        internal static string Step10_ConfirmOverwrite {
            get {
                return ResourceManager.GetString("Step10_ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm overwrite.
        /// </summary>
        internal static string Step10_ConfirmOverwriteCaption {
            get {
                return ResourceManager.GetString("Step10_ConfirmOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import now.
        /// </summary>
        internal static string Step10_ImportNow {
            get {
                return ResourceManager.GetString("Step10_ImportNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save import profile to file.
        /// </summary>
        internal static string Step10_SaveImportProfile {
            get {
                return ResourceManager.GetString("Step10_SaveImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import is in progress....
        /// </summary>
        internal static string Step11_ImportInProgress {
            get {
                return ResourceManager.GetString("Step11_ImportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking license....
        /// </summary>
        internal static string Step2_CheckingLicense {
            get {
                return ResourceManager.GetString("Step2_CheckingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Kentico version....
        /// </summary>
        internal static string Step2_CheckingVersion {
            get {
                return ResourceManager.GetString("Step2_CheckingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to SQL Server was successfully established..
        /// </summary>
        internal static string Step2_ConnectionSuccessful {
            get {
                return ResourceManager.GetString("Step2_ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to correct version of Kentico database was successfully established..
        /// </summary>
        internal static string Step2_ConnectionToDBSuccessfull {
            get {
                return ResourceManager.GetString("Step2_ConnectionToDBSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name:.
        /// </summary>
        internal static string Step2_Database {
            get {
                return ResourceManager.GetString("Step2_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to connect to the SQL server. The following error occurred:.
        /// </summary>
        internal static string Step2_ErrorConnectingDB {
            get {
                return ResourceManager.GetString("Step2_ErrorConnectingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish connection.
        /// </summary>
        internal static string Step2_EstablishConnection {
            get {
                return ResourceManager.GetString("Step2_EstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading SQL instances....
        /// </summary>
        internal static string Step2_LoadingInstances {
            get {
                return ResourceManager.GetString("Step2_LoadingInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are probably trying to connect to non-existent or non-Kentico database..
        /// </summary>
        internal static string Step2_OtherDB {
            get {
                return ResourceManager.GetString("Step2_OtherDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Step2_Password {
            get {
                return ResourceManager.GetString("Step2_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select database..
        /// </summary>
        internal static string Step2_SelectDatabase {
            get {
                return ResourceManager.GetString("Step2_SelectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server name or IP address:.
        /// </summary>
        internal static string Step2_ServerName {
            get {
                return ResourceManager.GetString("Step2_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify database name..
        /// </summary>
        internal static string Step2_SpecifyDBName {
            get {
                return ResourceManager.GetString("Step2_SpecifyDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify SQL server address..
        /// </summary>
        internal static string Step2_SpecifyServerAddress {
            get {
                return ResourceManager.GetString("Step2_SpecifyServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to specify user name..
        /// </summary>
        internal static string Step2_SpecifyUsername {
            get {
                return ResourceManager.GetString("Step2_SpecifyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to establish connection to the SQL Server....
        /// </summary>
        internal static string Step2_TryingToConnect {
            get {
                return ResourceManager.GetString("Step2_TryingToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SQL Server account.
        /// </summary>
        internal static string Step2_UseAccountName {
            get {
                return ResourceManager.GetString("Step2_UseAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string Step2_Username {
            get {
                return ResourceManager.GetString("Step2_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use integrated Windows authentication.
        /// </summary>
        internal static string Step2_UseTrustedConnection {
            get {
                return ResourceManager.GetString("Step2_UseTrustedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of selected Kentico database should be {0} (current database version is {1})..
        /// </summary>
        internal static string Step2_WrongVersion {
            get {
                return ResourceManager.GetString("Step2_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to domain controller was successfully established..
        /// </summary>
        internal static string Step3_ConnectionSuccessful {
            get {
                return ResourceManager.GetString("Step3_ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain controller name or IP address:.
        /// </summary>
        internal static string Step3_DCName {
            get {
                return ResourceManager.GetString("Step3_DCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Step3_Password {
            get {
                return ResourceManager.GetString("Step3_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify connection credentials (address, user name, password)..
        /// </summary>
        internal static string Step3_SpecifyConnection {
            get {
                return ResourceManager.GetString("Step3_SpecifyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify domain controller and logon credentials.
        /// </summary>
        internal static string Step3_SpecifyCredentials {
            get {
                return ResourceManager.GetString("Step3_SpecifyCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to establish connection to domain controller....
        /// </summary>
        internal static string Step3_TryingToConnect {
            get {
                return ResourceManager.GetString("Step3_TryingToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current domain controller and current user account.
        /// </summary>
        internal static string Step3_UseCurrentAccount {
            get {
                return ResourceManager.GetString("Step3_UseCurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string Step3_Username {
            get {
                return ResourceManager.GetString("Step3_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All groups.
        /// </summary>
        internal static string Step4_AllGroups {
            get {
                return ResourceManager.GetString("Step4_AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        internal static string Step4_AllUsers {
            get {
                return ResourceManager.GetString("Step4_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log import process to file.
        /// </summary>
        internal static string Step4_CreateLog {
            get {
                return ResourceManager.GetString("Step4_CreateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete users and roles that do not exist in the Active Directory.
        /// </summary>
        internal static string Step4_DeleteOldObjects {
            get {
                return ResourceManager.GetString("Step4_DeleteOldObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import all users from selected groups and ignore other users.
        /// </summary>
        internal static string Step4_ImportAllUsersOnlyFromSelectedRoles {
            get {
                return ResourceManager.GetString("Step4_ImportAllUsersOnlyFromSelectedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import groups:.
        /// </summary>
        internal static string Step4_ImportGroups {
            get {
                return ResourceManager.GetString("Step4_ImportGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new users only from selected groups.
        /// </summary>
        internal static string Step4_ImportNewUsersOnlyFromSelectedRoles {
            get {
                return ResourceManager.GetString("Step4_ImportNewUsersOnlyFromSelectedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import users:.
        /// </summary>
        internal static string Step4_ImportUsers {
            get {
                return ResourceManager.GetString("Step4_ImportUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected.
        /// </summary>
        internal static string Step4_OnlySelected {
            get {
                return ResourceManager.GetString("Step4_OnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sites:.
        /// </summary>
        internal static string Step4_SelectSites {
            get {
                return ResourceManager.GetString("Step4_SelectSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting ensures that newly imported users have to belong to at least one of the selected roles. Please note that this setting may override previous selection of users..
        /// </summary>
        internal static string Step4_ToolTipImportNewUsersOnlyFromSelectedRoles {
            get {
                return ResourceManager.GetString("Step4_ToolTipImportNewUsersOnlyFromSelectedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data of existing users and roles.
        /// </summary>
        internal static string Step4_UpdateData {
            get {
                return ResourceManager.GetString("Step4_UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update roles for existing Active Directory users.
        /// </summary>
        internal static string Step4_UpdateMemberships {
            get {
                return ResourceManager.GetString("Step4_UpdateMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates selected objects and imports objects that don&apos;t exist in Kentico (this setting is used for customized repetitive synchronization of Active Directory)..
        /// </summary>
        internal static string Step4_UpdateSelectedImportNew {
            get {
                return ResourceManager.GetString("Step4_UpdateSelectedImportNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected and import all new groups.
        /// </summary>
        internal static string Step4_UpdateSelectedImportNewGroups {
            get {
                return ResourceManager.GetString("Step4_UpdateSelectedImportNewGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected and import all new users.
        /// </summary>
        internal static string Step4_UpdateSelectedImportNewUsers {
            get {
                return ResourceManager.GetString("Step4_UpdateSelectedImportNewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import description:.
        /// </summary>
        internal static string Step5_ImportRoleDesc {
            get {
                return ResourceManager.GetString("Step5_ImportRoleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role code name format:.
        /// </summary>
        internal static string Step5_RoleCodeNameFormat {
            get {
                return ResourceManager.GetString("Step5_RoleCodeNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role display name format:.
        /// </summary>
        internal static string Step5_RoleDisplayNameFormat {
            get {
                return ResourceManager.GetString("Step5_RoleDisplayNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all attributes.
        /// </summary>
        internal static string Step5_ShowAllAttrs {
            get {
                return ResourceManager.GetString("Step5_ShowAllAttrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Step5_Source {
            get {
                return ResourceManager.GetString("Step5_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Step5_Target {
            get {
                return ResourceManager.GetString("Step5_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays advanced binding editor (displays all attributes from user&apos;s schema, doesn&apos;t show friendly names etc.).
        /// </summary>
        internal static string Step5_ToolTipAdvanced {
            get {
                return ResourceManager.GetString("Step5_ToolTipAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays simplified binding editor (excludes some fields, displays friendly strings, etc.).
        /// </summary>
        internal static string Step5_ToolTipSimple {
            get {
                return ResourceManager.GetString("Step5_ToolTipSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure new users as Kentico editors:.
        /// </summary>
        internal static string Step5_UserCMSEditor {
            get {
                return ResourceManager.GetString("Step5_UserCMSEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name format:.
        /// </summary>
        internal static string Step5_UsernameFormat {
            get {
                return ResourceManager.GetString("Step5_UsernameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes are being deselected....
        /// </summary>
        internal static string Step6_DeselectingNodes {
            get {
                return ResourceManager.GetString("Step6_DeselectingNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading active directory structure....
        /// </summary>
        internal static string Step6_LoadingADStruct {
            get {
                return ResourceManager.GetString("Step6_LoadingADStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select groups to be imported:.
        /// </summary>
        internal static string Step6_SelectGroups {
            get {
                return ResourceManager.GetString("Step6_SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes are being selected....
        /// </summary>
        internal static string Step6_SelectingNodes {
            get {
                return ResourceManager.GetString("Step6_SelectingNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select users to be imported:.
        /// </summary>
        internal static string Step6_UsersInGroup {
            get {
                return ResourceManager.GetString("Step6_UsersInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name/ Kentico user name:.
        /// </summary>
        internal static string Step7_DisplayUserName {
            get {
                return ResourceManager.GetString("Step7_DisplayUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading users....
        /// </summary>
        internal static string Step7_LoadingUsers {
            get {
                return ResourceManager.GetString("Step7_LoadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting names.
        /// </summary>
        internal static string Step8_ConflictsCaption {
            get {
                return ResourceManager.GetString("Step8_ConflictsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some conflicting group names were found. In order to successfully import all groups the role code name format should be &apos;Guid&apos;. Click &apos;Yes&apos; if you want to change role code name format automatically..
        /// </summary>
        internal static string Step8_ConflictsText {
            get {
                return ResourceManager.GetString("Step8_ConflictsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name / Kentico role name:.
        /// </summary>
        internal static string Step8_GroupName {
            get {
                return ResourceManager.GetString("Step8_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading groups....
        /// </summary>
        internal static string Step8_LoadingGroups {
            get {
                return ResourceManager.GetString("Step8_LoadingGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select roles:.
        /// </summary>
        internal static string Step9_SelectRoles {
            get {
                return ResourceManager.GetString("Step9_SelectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site:.
        /// </summary>
        internal static string Step9_Site {
            get {
                return ResourceManager.GetString("Step9_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose if you want to create a new import profile or use an existing one..
        /// </summary>
        internal static string StepDescription_1 {
            get {
                return ResourceManager.GetString("StepDescription_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose if you want to import the data now or/and save the import profile..
        /// </summary>
        internal static string StepDescription_10 {
            get {
                return ResourceManager.GetString("StepDescription_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that all selected data has been successfuly imported..
        /// </summary>
        internal static string StepDescription_11 {
            get {
                return ResourceManager.GetString("StepDescription_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the databse connection details..
        /// </summary>
        internal static string StepDescription_2 {
            get {
                return ResourceManager.GetString("StepDescription_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Active Directory controller details..
        /// </summary>
        internal static string StepDescription_3 {
            get {
                return ResourceManager.GetString("StepDescription_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust the settings of the import process..
        /// </summary>
        internal static string StepDescription_4 {
            get {
                return ResourceManager.GetString("StepDescription_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the user name and role name format and specify mapping of user fields..
        /// </summary>
        internal static string StepDescription_5 {
            get {
                return ResourceManager.GetString("StepDescription_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select users and groups to be imported into the Kentico database..
        /// </summary>
        internal static string StepDescription_6 {
            get {
                return ResourceManager.GetString("StepDescription_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust selected users..
        /// </summary>
        internal static string StepDescription_7 {
            get {
                return ResourceManager.GetString("StepDescription_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust selected groups..
        /// </summary>
        internal static string StepDescription_8 {
            get {
                return ResourceManager.GetString("StepDescription_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Kentico roles which the imported users will be assigned to..
        /// </summary>
        internal static string StepDescription_9 {
            get {
                return ResourceManager.GetString("StepDescription_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import profile.
        /// </summary>
        internal static string StepName_1 {
            get {
                return ResourceManager.GetString("StepName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        internal static string StepName_10 {
            get {
                return ResourceManager.GetString("StepName_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import log.
        /// </summary>
        internal static string StepName_11 {
            get {
                return ResourceManager.GetString("StepName_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Kentico database.
        /// </summary>
        internal static string StepName_2 {
            get {
                return ResourceManager.GetString("StepName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Active Directory controller.
        /// </summary>
        internal static string StepName_3 {
            get {
                return ResourceManager.GetString("StepName_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        internal static string StepName_4 {
            get {
                return ResourceManager.GetString("StepName_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field mapping.
        /// </summary>
        internal static string StepName_5 {
            get {
                return ResourceManager.GetString("StepName_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select users &amp; groups to be imported.
        /// </summary>
        internal static string StepName_6 {
            get {
                return ResourceManager.GetString("StepName_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust users to be imported.
        /// </summary>
        internal static string StepName_7 {
            get {
                return ResourceManager.GetString("StepName_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust groups to be imported.
        /// </summary>
        internal static string StepName_8 {
            get {
                return ResourceManager.GetString("StepName_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign imported users to Kentico roles.
        /// </summary>
        internal static string StepName_9 {
            get {
                return ResourceManager.GetString("StepName_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain\SAM (intranet\joe).
        /// </summary>
        internal static string Username_Format_DomainAndSAM {
            get {
                return ResourceManager.GetString("Username_Format_DomainAndSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM account name (joe).
        /// </summary>
        internal static string Username_Format_SAM {
            get {
                return ResourceManager.GetString("Username_Format_SAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPN (joe@intranet.mycompany.com).
        /// </summary>
        internal static string Username_Format_UPN {
            get {
                return ResourceManager.GetString("Username_Format_UPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Wizard_Back {
            get {
                return ResourceManager.GetString("Wizard_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Wizard_Cancel {
            get {
                return ResourceManager.GetString("Wizard_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel import?.
        /// </summary>
        internal static string Wizard_CancelImportConfirmation {
            get {
                return ResourceManager.GetString("Wizard_CancelImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel import.
        /// </summary>
        internal static string Wizard_CancelImportTitle {
            get {
                return ResourceManager.GetString("Wizard_CancelImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Wizard_Close {
            get {
                return ResourceManager.GetString("Wizard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the wizard?.
        /// </summary>
        internal static string Wizard_ConfirmExit {
            get {
                return ResourceManager.GetString("Wizard_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        internal static string Wizard_ConfirmExitCaption {
            get {
                return ResourceManager.GetString("Wizard_ConfirmExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Wizard_Finish {
            get {
                return ResourceManager.GetString("Wizard_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Wizard_Next {
            get {
                return ResourceManager.GetString("Wizard_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentico Active Directory Import Utility {0}.
        /// </summary>
        internal static string Wizard_Title {
            get {
                return ResourceManager.GetString("Wizard_Title", resourceCulture);
            }
        }
    }
}
