//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADImport.WinAppFoundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADImport.WinAppFoundation.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying site &apos;{0}&apos;..
        /// </summary>
        internal static string iisexpress_deploy {
            get {
                return ResourceManager.GetString("iisexpress.deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when deploying site &apos;{0}&apos;..
        /// </summary>
        internal static string iisexpress_deploymentfaild {
            get {
                return ResourceManager.GetString("iisexpress.deploymentfaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site &apos;{0}&apos; was successfully deployed..
        /// </summary>
        internal static string iisexpress_deploymentsucceeded {
            get {
                return ResourceManager.GetString("iisexpress.deploymentsucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when removing web project &quot;{0}&quot; from applicationhost.config..
        /// </summary>
        internal static string iisexpress_errorremovingfromconfig {
            get {
                return ResourceManager.GetString("iisexpress.errorremovingfromconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical path of web project &quot;{0}&quot; is null..
        /// </summary>
        internal static string iisexpress_physicalpathnull {
            get {
                return ResourceManager.GetString("iisexpress.physicalpathnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web project &quot;{0}&quot; has been removed from applicationhost.config..
        /// </summary>
        internal static string iisexpress_removedfromconfig {
            get {
                return ResourceManager.GetString("iisexpress.removedfromconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web project &quot;{0}&quot; is being removed from applicationhost.config..
        /// </summary>
        internal static string iisexpress_removingfromconfig {
            get {
                return ResourceManager.GetString("iisexpress.removingfromconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to stop site at &apos;{0}&apos;..
        /// </summary>
        internal static string iisexpress_stoppingsite {
            get {
                return ResourceManager.GetString("iisexpress.stoppingsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when stopping site &apos;{0}&apos;..
        /// </summary>
        internal static string iisexpress_stoppingsitefailed {
            get {
                return ResourceManager.GetString("iisexpress.stoppingsitefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site at &apos;{0}&apos; was successfully stopped..
        /// </summary>
        internal static string iisexpress_stoppingsitesucceeded {
            get {
                return ResourceManager.GetString("iisexpress.stoppingsitesucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site at &apos;{0}&apos; has already been stopped..
        /// </summary>
        internal static string iisexpress_stoppingstopped {
            get {
                return ResourceManager.GetString("iisexpress.stoppingstopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrive application pools from IIS configuration..
        /// </summary>
        internal static string iismanager_failedtogetpools {
            get {
                return ResourceManager.GetString("iismanager.failedtogetpools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve sites from IIS configuration..
        /// </summary>
        internal static string iismanager_failedtogetsites {
            get {
                return ResourceManager.GetString("iismanager.failedtogetsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve IIS directory..
        /// </summary>
        internal static string iismanager_iisdirectoryfailed {
            get {
                return ResourceManager.GetString("iismanager.iisdirectoryfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create server manager for IIS manipulation..
        /// </summary>
        internal static string iismanager_servermanagerfailed {
            get {
                return ResourceManager.GetString("iismanager.servermanagerfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website &apos;{0}&apos; ({1}) is not valid..
        /// </summary>
        internal static string iismanager_websitevalidationfailed {
            get {
                return ResourceManager.GetString("iismanager.websitevalidationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning SYSADMIN role to user &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_assignsysadmintouser {
            get {
                return ResourceManager.GetString("localdb.assignsysadmintouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reconfigure LocalDB instance. After a while being idle it will stop..
        /// </summary>
        internal static string localdb_autostopdisablefailed {
            get {
                return ResourceManager.GetString("localdb.autostopdisablefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance successfully reconfigured so it does not stop when idle..
        /// </summary>
        internal static string localdb_autostopdisablesuccess {
            get {
                return ResourceManager.GetString("localdb.autostopdisablesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring LocalDB instance does not stop when idle..
        /// </summary>
        internal static string localdb_autostopdisabling {
            get {
                return ResourceManager.GetString("localdb.autostopdisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing connection to LocalDB server instance..
        /// </summary>
        internal static string localdb_closingconnection {
            get {
                return ResourceManager.GetString("localdb.closingconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing connection to LocalDB server instance failed..
        /// </summary>
        internal static string localdb_closingconnectionfailed {
            get {
                return ResourceManager.GetString("localdb.closingconnectionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to LocalDB server instance closed..
        /// </summary>
        internal static string localdb_connectionclosed {
            get {
                return ResourceManager.GetString("localdb.connectionclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; has been created..
        /// </summary>
        internal static string localdb_created {
            get {
                return ResourceManager.GetString("localdb.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; was not created. Executable produced an empty output or instance was not detected. Output : {1}.
        /// </summary>
        internal static string localdb_createfailed {
            get {
                return ResourceManager.GetString("localdb.createfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when creating LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_createfailedexception {
            get {
                return ResourceManager.GetString("localdb.createfailedexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_creating {
            get {
                return ResourceManager.GetString("localdb.creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating user &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_creatinguser {
            get {
                return ResourceManager.GetString("localdb.creatinguser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when creating user &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_creatinguserfailed {
            get {
                return ResourceManager.GetString("localdb.creatinguserfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when getting info about instances..
        /// </summary>
        internal static string localdb_getinginfofailed {
            get {
                return ResourceManager.GetString("localdb.getinginfofailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting LocalDB instance &quot;{0}&quot; failed. Instance is not running after start finished. Output : {1}.
        /// </summary>
        internal static string localdb_notrunningafterstart {
            get {
                return ResourceManager.GetString("localdb.notrunningafterstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal of LocalDB instance &quot;{0}&quot; failed. Instance is present after removal. Output : {1}.
        /// </summary>
        internal static string localdb_presentafterremoval {
            get {
                return ResourceManager.GetString("localdb.presentafterremoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when removing LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_removalfailed {
            get {
                return ResourceManager.GetString("localdb.removalfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; has been removed..
        /// </summary>
        internal static string localdb_removed {
            get {
                return ResourceManager.GetString("localdb.removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_removing {
            get {
                return ResourceManager.GetString("localdb.removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping LocalDB instance &quot;{0}&quot; failed. Instance is running after stop finished. Output : {1}.
        /// </summary>
        internal static string localdb_runningafterstop {
            get {
                return ResourceManager.GetString("localdb.runningafterstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; has been shared. Shared name is &quot;{1}&quot;..
        /// </summary>
        internal static string localdb_shared {
            get {
                return ResourceManager.GetString("localdb.shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing LocalDB instance &quot;{0}&quot;. Shared name will be &quot;{1}&quot;..
        /// </summary>
        internal static string localdb_sharing {
            get {
                return ResourceManager.GetString("localdb.sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; was not shared. Shared instance &quot;{1}&quot; was not detected. Output : {2}.
        /// </summary>
        internal static string localdb_sharingfailed {
            get {
                return ResourceManager.GetString("localdb.sharingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when sharing LocalDB instance &quot;{0}&quot; with &quot;{1}&quot;..
        /// </summary>
        internal static string localdb_sharingfailedexception {
            get {
                return ResourceManager.GetString("localdb.sharingfailedexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; has been started..
        /// </summary>
        internal static string localdb_started {
            get {
                return ResourceManager.GetString("localdb.started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_starting {
            get {
                return ResourceManager.GetString("localdb.starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when starting LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_startingfailed {
            get {
                return ResourceManager.GetString("localdb.startingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping LocalDB instance &quot;{0}&quot; before removal..
        /// </summary>
        internal static string localdb_stopingbeforeremoval {
            get {
                return ResourceManager.GetString("localdb.stopingbeforeremoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{0}&quot; has been stopped..
        /// </summary>
        internal static string localdb_stopped {
            get {
                return ResourceManager.GetString("localdb.stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_stopping {
            get {
                return ResourceManager.GetString("localdb.stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when stopping LocalDB instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_stoppingfailed {
            get {
                return ResourceManager.GetString("localdb.stoppingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{1}&quot; has been unshared from &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_unshared {
            get {
                return ResourceManager.GetString("localdb.unshared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharing LocalDB instance &quot;{1}&quot; from &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_unsharing {
            get {
                return ResourceManager.GetString("localdb.unsharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB instance &quot;{1}&quot; was not unshared from &quot;{0}&quot;. Shared instance &quot;{1}&quot; is still being detected. Output : {2}.
        /// </summary>
        internal static string localdb_unsharingfailed {
            get {
                return ResourceManager.GetString("localdb.unsharingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when unsharing LocalDB instance &quot;{1}&quot; from instance &quot;{0}&quot;..
        /// </summary>
        internal static string localdb_unsharingfailedexception {
            get {
                return ResourceManager.GetString("localdb.unsharingfailedexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path contains invalid characters..
        /// </summary>
        internal static string path_containsinvalidchars {
            get {
                return ResourceManager.GetString("path.containsinvalidchars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to selected folder has been denied..
        /// </summary>
        internal static string path_deniedaccess {
            get {
                return ResourceManager.GetString("path.deniedaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder is not empty..
        /// </summary>
        internal static string path_directorynotempty {
            get {
                return ResourceManager.GetString("path.directorynotempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon in the path must be part of volume identifier..
        /// </summary>
        internal static string path_invalidcolon {
            get {
                return ResourceManager.GetString("path.invalidcolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; is not valid. ({1}).
        /// </summary>
        internal static string path_isnotvalid {
            get {
                return ResourceManager.GetString("path.isnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is too long..
        /// </summary>
        internal static string path_istoolong {
            get {
                return ResourceManager.GetString("path.istoolong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must not be empty..
        /// </summary>
        internal static string path_mustnotbeempty {
            get {
                return ResourceManager.GetString("path.mustnotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist..
        /// </summary>
        internal static string path_pathdoesnotexist {
            get {
                return ResourceManager.GetString("path.pathdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative path is not allowed..
        /// </summary>
        internal static string path_pathisrelativepath {
            get {
                return ResourceManager.GetString("path.pathisrelativepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when closing main window of process with ID &quot;{0}&quot;..
        /// </summary>
        internal static string process_colsingmainwindowsfailed {
            get {
                return ResourceManager.GetString("process.colsingmainwindowsfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when getting main module of process &quot;{0}&quot;..
        /// </summary>
        internal static string process_gettingmainmodulefailed {
            get {
                return ResourceManager.GetString("process.gettingmainmodulefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process with ID &quot;{0}&quot; has been started..
        /// </summary>
        internal static string process_started {
            get {
                return ResourceManager.GetString("process.started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process with ID &quot;{0}&quot; is being started..
        /// </summary>
        internal static string process_starting {
            get {
                return ResourceManager.GetString("process.starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when starting process with ID &quot;{0}&quot;..
        /// </summary>
        internal static string process_startingfailed {
            get {
                return ResourceManager.GetString("process.startingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process with ID &quot;{0}&quot; has been stopped..
        /// </summary>
        internal static string process_stopped {
            get {
                return ResourceManager.GetString("process.stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process with ID &quot;{0}&quot; is being stopped..
        /// </summary>
        internal static string process_stopping {
            get {
                return ResourceManager.GetString("process.stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when stopping process with ID &quot;{0}&quot;..
        /// </summary>
        internal static string process_stoppingfailed {
            get {
                return ResourceManager.GetString("process.stoppingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; has been started..
        /// </summary>
        internal static string service_started {
            get {
                return ResourceManager.GetString("service.started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; is being started..
        /// </summary>
        internal static string service_starting {
            get {
                return ResourceManager.GetString("service.starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when starting service &quot;{0}&quot;..
        /// </summary>
        internal static string service_startingfailed {
            get {
                return ResourceManager.GetString("service.startingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; has been stopped..
        /// </summary>
        internal static string service_stopped {
            get {
                return ResourceManager.GetString("service.stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; is being stopped..
        /// </summary>
        internal static string service_stopping {
            get {
                return ResourceManager.GetString("service.stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when stopping service &quot;{0}&quot;..
        /// </summary>
        internal static string service_stoppingfailed {
            get {
                return ResourceManager.GetString("service.stoppingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service control returned exit code &quot;{1}&quot; when stopping service &quot;{0}&quot;..
        /// </summary>
        internal static string service_stoppingreturnedwrongexitcode {
            get {
                return ResourceManager.GetString("service.stoppingreturnedwrongexitcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; has been uninstalled..
        /// </summary>
        internal static string service_uninstalled {
            get {
                return ResourceManager.GetString("service.uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; is being uninstalled..
        /// </summary>
        internal static string service_uninstalling {
            get {
                return ResourceManager.GetString("service.uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when uninstalling service &quot;{0}&quot;..
        /// </summary>
        internal static string service_uninstallingfailed {
            get {
                return ResourceManager.GetString("service.uninstallingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service control returned exit code &quot;{1}&quot; when uninstalling service &quot;{0}&quot;..
        /// </summary>
        internal static string service_uninstallreturnedwrongexitcode {
            get {
                return ResourceManager.GetString("service.uninstallreturnedwrongexitcode", resourceCulture);
            }
        }
    }
}
